site_title = "Robot Papers"
limit_days = 7

[[sources]]
limit = 300
category = "cs.RO"
title = "Robotics"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
